config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, :controllers => {registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks"  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :trips
  
  resources :idea_boards, only: [:show] do
    resources :ideas, only: [:show, :new]
  end

  resources :ideas

  resources :trip_users, only: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ActiveRecord::Base
    scope :filter_by_user,->  (user_id) { where("user_id = ?", user_id) }

    belongs_to :idea_board
    belongs_to :trip_user

end

app/models/idea_board.rb
class IdeaBoard < ActiveRecord::Base
    has_many :ideas
    belongs_to :trip
    has_many :trip_users, through: :ideas
end

app/models/trip.rb
class Trip < ActiveRecord::Base
    has_one :idea_board
    has_many :trip_users
    has_many :users, through: :trip_user
    has_many :ideas, through: :idea_board

    # Add validations for Title:String
    validates :title, presence: true

    # Add accepts_nested_attributes for :trip_user(s)
    accepts_nested_attributes_for :trip_users
    accepts_nested_attributes_for :idea_board

    # Add setter method for trip_users attributes
    def trip_users_attributes=(trip_user_attributes)
        if !(trip_user_attributes['user_id'].blank?)
            trip_user = TripUser.find_or_create_by(trip_user_attributes)
            self.trip_users << trip_user
        end
    end

    def user_type_selections
        user_types = ['Administrator', 'Contributer']
    end
end

app/models/trip_user.rb
class TripUser < ActiveRecord::Base
    belongs_to :trip
    belongs_to :user
    has_many :ideas

    def user_type_selections
        user_types = ['Administrator', 'Contributer']
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trip_users
  has_many :trips, through: :trip_users
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :github, :google_oauth2]

         def self.from_omniauth(auth)
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
          user.email = auth.info.email
          user.password = Devise.friendly_token[0,20]
        end      
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!

    def after_sign_in_path_for(resource)
        request.env['omniauth.origin'] || trips_path
    end
    
    private
    
    def model_params(model_name, *args)
        params.require(model_name).permit(*args)
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :authenticate_user!
    def index
    end
end

app/controllers/idea_boards_controller.rb
class IdeaBoardsController < ApplicationController
    before_action :initialize_search, only: :show

    def show
        @idea_board = IdeaBoard.find_by(params[:id])
        handle_filters
    end

    def clear
        clear_session(:filter_option)
        redirect_to idea_boards_path
    end

    private

    def idea_board_params
        model_params(:idea_board, :name, :trip_id)
    end

    def initialize_search
        params[:filter_option] = nil if params[:filter_option].blank?
        session[:filter_option] = params[:filter_option]
    end

    def handle_filters
        if session[:filter_option]
            @user = Idea.filter_by_user(session[:filter_option])
        end
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    def new
        @idea = Idea.new(idea_board_id: params[:idea_board_id])
    end

    def create
        @idea = Idea.new(ideas_params)

        if @idea.save
            redirect_to idea_board_idea_path(@idea, @idea.idea_board_id)
        end
    end

    def show
        @idea = Idea.find_by_id(params[:id])
    end

    private

    def ideas_params
        model_params(:idea, :title, :about, :price, :idea_board_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

    def index
        @trips = current_user.trips
    end
    
    def new
        @trip = Trip.new
        @trip.trip_users.build(user_type: 'contributer')
        @trip.trip_users.build(user_type: 'contributer')
        @trip.trip_users.build(user_type: 'contributer')
        @trip.build_idea_board(name: 'Idea Board')
    end

    def create
        @trip = Trip.new(trip_params)

        if @trip.save
            trip_usr_admin = @trip.trip_users.build(user_id: current_user.id, user_type: 'Administrator')
            trip_usr_admin.save
            redirect_to trip_path(@trip)
        end
    end

    def show
        @trip = Trip.find_by_id(params[:id])
    end

    def edit
        @trip = Trip.find_by_id(params[:id])
    end

    private

    def trip_params
        model_params(
            :trip,
            :title,
            trip_users_attributes: [
                :user_id,
                :user_type
            ],
            idea_board_attributes: [
                :name
            ]
        )
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
       @user = User.from_omniauth(request.env["omniauth.auth"])
       sign_in_and_redirect @user      
    end

    def github
       @user = User.from_omniauth(request.env["omniauth.auth"])
       sign_in_and_redirect @user  
    end

    def google_oauth2
       @user = User.from_omniauth(request.env["omniauth.auth"])
       sign_in_and_redirect @user  
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="container">
    <div class="row">
        <h1>Welcome TravelR!</h1>
    </div>
    <div class="row">
        <p>Merry and well met! If this is your first time visiting our site, let me tell you a little about ourselves.</p>

        <p>TravelR is a platform for users, their friends and family to plan and blog about their journey.</p>
    </div>
    <!-- Have a Breakdown of all the different elements that TravelR does -->
    <div class="row">
        <div class="col-md-3">
        <p>Ready to get started?</p>

        <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-primary" %>
        </div>
    </div>
</div>

app/views/idea_boards/_navibar.html.erb
<div class="col-md pb-3 d-flex justify-content-right">
    <%= link_to 'Add New Idea', new_idea_board_idea_path(idea_b), class: "btn btn-primary" %>
</div>

app/views/idea_boards/show.html.erb
<!-- This view will show all of our Ideas and give use the option to create a new Idea -->
<div class="container">
    <% if @idea_board.ideas.blank? %>
        <div class="row">
            <p>It doesn't look like you have any ideas yet.</p>
            <p>Let's Create One!</p>
            <button><%= link_to 'New idea', new_idea_board_idea_path(@idea_board) %></button>
    <% else %>
        <div class="row">
            <%= render partial: 'navibar', locals: { idea_b: @idea_board } %>
        </div>
        <div class="row pb-3">
            <div class="col-md d-flex justify-content-right">
                <%= form_for @idea_board, as: :idea_board, url: idea_board_path(@idea_board), method: :get do |f| %>
                    <select name="filter_option" onchange="this.form.submit()">
                        <option value="">Pick a User</option>
                        <% @idea_board.trip_users.each do |trip_user| %>
                            <option value="<%= trip_user.id %>"><%= trip_user.user.email %></option>
                        <% end %>
                    </select>
                <% end %>
            </div>
        </div>

        <div class="row">
            <% @idea_board.ideas.each do |idea| %>
                <div class="col-md-4 col-sm-6 cell-box">
                    <div class="card idea-listings" style="width: 18rem;">
                        <!-- image goes here -->
                        <div class="card-body">
                            <h5 class="card-title"><%= idea.title %></h5>
                            <p class="card-text"><%= idea.about %></p>
                            <%= link_to 'View More', idea_path(idea), class: "btn btn-primary"%>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/ideas/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-md pt-3 pb-3 d-flex justify-content-center">
            <%= form_for(@idea) do |f| %>
                <%= f.hidden_field :idea_board_id %>
                <%= f.label 'Title:' %><br>
                <%= f.text_field :title %><br>
                <%= f.label 'About:' %><br>
                <%= f.text_area :about %><br>
                <%= f.label 'Price:' %><br>
                <%= f.text_field :price %><br>
                <%= f.submit %>
            <% end %>
        </div>
    </div>
</div>

app/views/ideas/edit.html.erb
<%= render 'form' %>

app/views/ideas/new.html.erb
<%= render 'form' %>

app/views/ideas/show.html.erb
<div class="container">
    <div class="row">
        <h1><%= @idea.title %></h1>
    </div>
    <div class="row">
        <h5>About</h5>
    </div>
    <div class="row">
        <p><%= @idea.about %></p>
    </div>
    <div class="row">
        <h5>Price</h5>
    </div>
    <div class="row">
        <p>$<%= '%.2f' % @idea.price %></p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <br>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="d-flex flex-grow-1">
        <span class="w-100 d-lg-none d-block"><!-- hidden spacer to center brand on mobile --></span>
        <a class="navbar-brand d-none d-lg-inline-block" href="/">
            TravelR
        </a>
        <a class="navbar-brand-two mx-auto d-lg-none d-inline-block" href="/">
            <img src="//placehold.it/40?text=LOGO" alt="logo">
        </a>
        <div class="w-100 text-right">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
    <div class="collapse navbar-collapse flex-grow-1 text-right" id="myNavbar">
        <ul class="navbar-nav ml-auto flex-nowrap">
            <li class="nav-item">
                <%= link_to 'Home', '/', class: "nav-link m-2 menu-item nav-active"%>
            </li>
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to 'Trips', trips_path, class: "nav-link m-2 menu-item" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Settings', '#', class: "nav-link m-2 menu-item" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Contact', '#', class: "nav-link m-2 menu-item" %>
                </li>
                <li class="nav-item">
                    <%= button_to('Sign Out', destroy_user_session_path, method: "delete", class: "m-2 menu-item") %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to 'Log In', new_user_session_path, class: "nav-link m-2 menu-item" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link m-2 menu-item btn btn-primary" %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/trips/_navibar.html.erb
<div class="col-md pt-3 pb-3">
    <%= link_to 'Invite Users', new_trip_user_path, class: "p-1" %>
    <%= link_to 'Settings', edit_trip_path(trip), class: "p-1" %>
</div>

app/views/trips/_trips.html.erb
<% user_trips.each do |trip| %>
    <div class="col-md-4 col-sm-6 cell-box">
        <div class="card trip-listings" style="width: 18rem;">
            <!-- image goes here -->
            <div class="card-body">
                <h5 class="card-title"><%= trip.title %></h5>
                <%= link_to 'View More', trip_path(trip), class: "btn btn-primary"%>
            </div>
        </div>
    </div>
<% end %>

app/views/trips/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md pt-3 pb-3">
            <div class="d-flex justify-content-center">
                <h1>Trip Settings</h1>
            </div>
            <div class="d-flex justify-content-center">
                <%= form_for @trip do |f| %>
                    <%= f.label :title %><br>
                    <%= f.text_field :title %><br><br>

                    <%= f.fields_for :idea_board do |idea_b| %>
                        <%= idea_b.label :name %><br>
                        <%= idea_b.text_field :name %><br><br>
                    <% end %>

                    <%= f.submit %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/trips/index.html.erb
<div class="container">  
    <% if @trips.empty? %>
        <div class="row">
            <div class="col-md pt-3 d-flex justify-content-center">
                <p>You don't have any trips yet!</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md d-flex justify-content-center">
                <button><%= link_to 'Create New Trip', new_trip_path %></button>
            </div>
        </div>
    <% else %>
        <div class="row">
            <%= render partial: "trips", locals: {user_trips: @trips} %>
        </div>
    <% end %>
</div>

app/views/trips/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md pt-3 pb-3">
            <div class="d-flex justify-content-center">
                <h1>New Trip Form</h1>
            </div>
            <div class="d-flex justify-content-center">
                <%= form_for @trip do |f| %>
                    <%= f.label :title %>
                    <%= f.text_field :title %><br>

                    <%= f.fields_for :trip_users do |trip_usr| %>
                        <%= trip_usr.label 'Email:'%>
                        <%= trip_usr.text_field :user_id %>

                        <%= trip_usr.hidden_field :user_type, :value => 'Contributer' %><br>
                    <% end %>

                    <%= f.fields_for :idea_board do |idea_b| %>
                        <%= idea_b.hidden_field :name %>
                    <% end %>

                    <%= f.submit %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/trips/show.html.erb
<div class="container">
    <div class="row">
        <%= render partial: 'navibar', locals: { trip: @trip } %>
    </div>
    <div class="row">
        <div class="col-md pt-3 pb-3">
            <h1><%= @trip.title %></h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md pt-3 pb-3">
            <%= link_to @trip.idea_board.name, idea_board_path(@trip.idea_board) %>
        </div>
    </div>
</div>